spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newsdb?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  properties:
     hibernate:
       dialect:org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8085
